export const metadataPages = {
    main:{
        title: 'ร้านค้าออนไลน์ที่คุณเชื่อถือได้ | Goodlistseller', 
        description: 'แพลตฟอร์มที่ช่วยให้คุณค้นหาร้านค้าออนไลน์ที่เชื่อถือได้ในประเทศไทย',
        keywords: ["Goodlistseller", "Goodlistseller", "Goodlistseller"],
        author: "Goodlistseller",
        robots: "index, follow",
        viewport: "width=device-width, initial-scale=1",
    },
    report:{
        title: "รายงานร้านค้า | Goodlistseller",
        description: "รายงานร้านค้าที่มีความสงสัย",
        keywords: ["Goodlistseller", "Goodlistseller", "Goodlistseller"],
        author: "Goodlistseller",
        robots: "index, follow",
        viewport: "width=device-width, initial-scale=1",
    },
    profile:{
        title: "โปรไฟล์ | Goodlistseller",
        description: "โปรไฟล์ของคุณ",
        keywords: ["Goodlistseller", "Goodlistseller", "Goodlistseller"],
        author: "Goodlistseller",
        robots: "index, follow",
    },
    stores:{
        title: 'ร้านค้าที่ผ่านการตรวจสอบ | Goodlistseller',  
        description: 'ค้นหาร้านค้าออนไลน์ที่ผ่านการตรวจสอบและเชื่อถือได้',
        keywords: ["Goodlistseller", "Goodlistseller", "Goodlistseller"],
        author: "Goodlistseller",
        robots: "index, follow",    
    },
    admin:{
        title: "ระบบจัดการร้านค้า | Goodlistseller",
        description: "ระบบจัดการร้านค้า",
        keywords: ["Goodlistseller", "Goodlistseller", "Goodlistseller"],
        author: "Goodlistseller",
        robots: "index, follow",
    },
    verify:{
        title: "ยืนยันตัวตนของคุณ | Goodlistseller",
        description: "ยืนยันตัวตนของคุณเพื่อใช้งานระบบ",
        keywords: ["Goodlistseller", "Goodlistseller", "Goodlistseller"],
        author: "Goodlistseller",
        robots: "index, follow",
    },
    login:{
        title: "เข้าสู่ระบบ | Goodlistseller",
        description: "เข้าสู่ระบบเพื่อใช้งาน Goodlistseller ค้นหาร้านค้าออนไลน์ที่น่าเชื่อถือและแชร์ประสบการณ์การซื้อสินค้า",
        keywords: ["Goodlistseller", "Goodlistseller", "Goodlistseller"],
        author: "Goodlistseller",
        robots: "index, follow",
    },
    signup:{
        title: "สมัครสมาชิก | Goodlistseller",
        description: "สมัครสมาชิกเพื่อใช้งาน Goodlistseller ค้นหาร้านค้าออนไลน์ที่น่าเชื่อถือและแชร์ประสบการณ์การซื้อสินค้า",
        keywords: ["Goodlistseller", "Goodlistseller", "Goodlistseller"],
        author: "Goodlistseller",
        robots: "index, follow",
    },
    "reset-password":{
        title: "รีเซ็ตรหัสผ่าน | Goodlistseller",
        description: "รีเซ็ตรหัสผ่านเพื่อใช้งาน Goodlistseller ค้นหาร้านค้าออนไลน์ที่น่าเชื่อถือและแชร์ประสบการณ์การซื้อสินค้า",
        keywords: ["Goodlistseller", "Goodlistseller", "Goodlistseller"],
        author: "Goodlistseller",
        robots: "index, follow",
    },
    // contact:{  
    //     title: 'ติดต่อเรา | Goodlistseller',
    //     description: 'ติดต่อทีมงาน Goodlistseller - แพลตฟอร์มร้านค้าออนไลน์ที่น่าเชื่อถือในประเทศไทย',
    //     keywords: ["Goodlistseller", "Goodlistseller", "Goodlistseller"],
    //     author: "Goodlistseller",
    //     robots: "index, follow",
    // },
    "blog-management":{
        title: "จัดการบทความ | Goodlistseller",
        description: "จัดการบทความ",
        keywords: ["Goodlistseller", "Goodlistseller", "Goodlistseller"],
        author: "Goodlistseller",
        robots: "index, follow",
    },
    "new-blog":{
        title: "สร้างบทความใหม่ | Goodlistseller",
        description: "สร้างบทความใหม่",
        keywords: ["Goodlistseller", "Goodlistseller", "Goodlistseller"],
        author: "Goodlistseller",
        robots: "index, follow",
    },
    "edit-blog":{
        title: "แก้ไขบทความ | Goodlistseller",
        description: "แก้ไขบทความ",
        keywords: ["Goodlistseller", "Goodlistseller", "Goodlistseller"],
        author: "Goodlistseller",
        robots: "index, follow",
    }
}
